var bronze_star_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=bronze+star&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var bronze_medallion_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=bronze+medallion&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var bronze_cross_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=bronze+cross&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var standard_first_aid_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=standard+first+aid&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var national_lifeguard_pool_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=National+lifeguard+pool&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var national_lifeguard_water_park_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=National+lifeguard+water+park&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var lifesaving_instructor_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=lifesaving+instructor&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var assistant_water_safety_instructor_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=awsi&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var water_safety_instructor_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=water+safety+instructor&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var fitness_theory_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=fitness+theory+module&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';
var instructor_aquafit_url='http://www.surrey.ca/culture-recreation/1697.aspx?form=4&waitListed=1&sortBy=&facilitySort=sort%3D0%7Cdisplay%3D50&keywords=Instructor+aquafit+module&frmSubmit=Search&showFilters=false&daysChecked=1%2C2%2C3%2C4%2C5%2C6%2C7&townCentres=1&startDate=Jul-24-2015&endDate=&startTime=&endTime=&day_search=1&day_search=2&day_search=3&day_search=4&day_search=5&day_search=6&day_search=7&participant_age_1=&participant_max_price_1=&numParticipants=1&within_distance=&within_address=&townCentreIds=3&townCentreIds=4&townCentreIds=7&townCentreIds=5&townCentreIds=8&townCentreIds=6&facilityTypeID=&inDoorActivity=1&outDoorActivity=1&inDoorActivity=1&outDoorActivity=1&rgProgram=1&dropIn=1&rgProgram=1&dropIn=1&waitList=1&categoryID=&facilityID=';

var result_urls={
	'bronze_star': bronze_star_url,
	'bronze_medallion':bronze_medallion_url,
	'bronze_cross':bronze_cross_url,
	'standard_first_aid':standard_first_aid_url,
	'national_lifeguard_pool':national_lifeguard_pool_url,
	'national_lifeguard_water_park':national_lifeguard_water_park_url,
	'lifesaving_instructor':lifesaving_instructor_url,
	'assistant_water_safety_instructor':assistant_water_safety_instructor_url,
	'water_safety_instructor':water_safety_instructor_url,
	'fitness_theory':fitness_theory_url,
	'instructor_aquafit':instructor_aquafit_url
} 